# Generated by Django 5.0.3 on 2024-04-03 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('rounding_corners', models.BooleanField(verbose_name='Скругленныые края')),
                ('embossing', models.BooleanField(verbose_name='Тиснение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kuaranti.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Визитка',
                'verbose_name_plural': 'Визитки',
            },
        ),
    ]
